services:
  - type: web
    name: tokn
    runtime: docker
    repo: https://github.com/cordfuse/tokn
    branch: main
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: TOKN_API_KEY
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
